### ISSUE TITLE
Add an feature to export parameters by default

### ISSUE THREAD

**Issue by antoine-morvan** [FZJ-JSC/JUBE#5]
Hello, 

My current input looks like this :
```yaml
parameterset:
  - name: build_parameters
    parameter: 
    - {name: COMPILER,      export: true, _: "gcc:13.2.0,llvm:17.0.6"}
    - {name: BUILD_FLAG,    export: true, _: "default"}
    - {name: MPI,           export: true, _: "openmpi:4.1.6"}
    - {name: KOKKOS,        export: true, _: "kokkos:4.1.0"}
    - {name: HDF5_PARALLEL, export: true, _: "hdf5-parallel:1.14.3"}
  - name: run_parameters
    parameter: 
    - {name: testcase,  export: true, _: "short"}
    - {name: bindings,  export: true, _: "socket:off:any"}
    - {name: FREQ,      export: true, _: "NOMINAL"}
```

Is there a way to export all the parameters by default ? I could not find anything related to this in the documentation.

Best,
Antoine.
