### ISSUE TITLE
Dependency graph instead of tree

### ISSUE THREAD

**Issue by antoine-morvan** [FZJ-JSC/JUBE#6]
Hello,

Currently, it seems to me that the dependencies we can express in the JUBE input can only be a tree. For instance, my input could look like this : 

```yaml
name: testjube
outpath: testjube_bench
comment: Test JUBE

#Configuration
parameterset:
  - name: build_parameters
    parameter: 
    - {name: COMPILER,    _: "gcc:13.2.0,llvm:17.0.6"}
  - name: run_parameters
    parameter: 
    - {name: FREQ,            _: "NOMINAL,TURBO"}

#Operation
step:
  - name: prepare
    do: |
      echo "do the prepare"
  - name: build
    depend: prepare
    use: build_parameters
    do: |
      echo "do the build"
  - name: setup
    depend: build
    use: build_parameters, run_parameters
    do: |
      echo "do the build"
  - name: run
    depend: setup
    use: build_parameters, run_parameters
    do: |
      echo "do the build"
```

For the input above, the dependency of the steps would look like this :

```mermaid
graph TD;
    prepare-->build_gcc:13.2.0;
    build_gcc:13.2.0-->setup_gcc:13.2.0_NOMINAL;
    build_gcc:13.2.0-->setup_gcc:13.2.0_TURBO;
    setup_gcc:13.2.0_TURBO-->run_gcc:13.2.0_TURBO;
    setup_gcc:13.2.0_NOMINAL-->run_gcc:13.2.0_NOMINAL

    prepare-->build_llvm:17.0.6;
    build_llvm:17.0.6-->setup_llvm:17.0.6_NOMINAL;
    build_llvm:17.0.6-->setup_llvm:17.0.6_TURBO;
    setup_llvm:17.0.6_TURBO-->run_llvm:17.0.6_TURBO;
    setup_llvm:17.0.6_NOMINAL-->run_llvm:17.0.6_NOMINAL
```

However, my setup step is a bit costly in terms of compute resources, but not meaningful in terms of results (analysis): it simply produces some intermediate input from built binaries. Actually, I want to run it once only, using whatever of the build and run parameter that are specified. The dependencies I would like to express would look like this :

**Comment by thobreuer** [comment]
- Hint: since the setup step depend on the build step, the parametersets used in the build will automatically be available in the setup step without using them explicitly (see my example below). 
- What you are probably looking for is a `shared` `step` with a `shared` `do` as a solution for the setup step. JUBE will still create the four directories (as in your first graph), but the shared to will only be exeuted once for all four workpackages of the setup step. See also our adv. tutorial section about shared-operations: https://apps.fz-juelich.de/jsc/jube/jube2/docu/advanced.html#shared-operations

```
name: testjube
outpath: testjube_bench
comment: TEST

#Configuration
parameterset:
  - name: build_parameters
    parameter:
    - {name: COMPILER,    _: "gcc:13.2.0,llvm:17.0.6"}
  - name: run_parameters
    parameter:
    - {name: FREQ,            _: "NOMINAL,TURBO"}

#Operation
step:
  - name: prepare
    do: |
      echo "do the prepare"
  - name: build
    depend: prepare
    use: build_parameters
    do: |
      echo "do the build: $COMPILER"
  - name: setup
    depend: build
    use: run_parameters
    shared: share
    do:
      - 'echo "do the setup: $COMPILER $FREQ"'
      - {shared: true, _: 'echo "IN SHARED"'}
  - name: run
    depend: setup
    do: |
      echo "do the run: $COMPILER $FREQ"
```
